### PR TITLE
No force of 'always on top' anymore

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by d-s-x** [comment]
Looks like there is a lot of unrelated commits (like 39ee4c3 944c3e1 ad2fbb1). I wont accept a PR like this.
Normally you can do an interactive rebase and fix all of this but I'm not sure github allows this.

Also can you please give some description for you PR. "No force of 'always on top' anymore" isn't clear enough. Have you tried to select "context menu -> **Window -> Stays on top -> Off**"? It worked quite fine for me (but I personally prefer "Playing" mode)

**Comment by ShalokShalom** [comment]
I already wrote you an email, in which i ask you to simpy ignore these PR - i am a beginner and didnt knew what i do at all. The commit with 'not always on top' is not enough and blocks compiling, i am still working on it just right now, the aim is to ship a Bomi which does not come with this behavior in the beginning. 

Is there a method to preselect **Off**?

And what belongs the other 2 commits: They are already in your development branch.
I dont know, how they come into this PR, as said, this stuff here is new to me ;) 

EDIT: I also forgot about the option to comment here, thats why the email.

**Comment by d-s-x** [comment]
@ShalokShalom,

> the aim is to ship a Bomi which does not come with this behavior in the beginning.
> Is there a method to preselect Off?

Obviously there should be a way to change default preferences but why bother. Just set it to "Off" once.

**Comment by ShalokShalom** [comment]
Because i want to ship it with Off.

**Pull request closed without merging**
